project:
  type: website
  output-dir: docs
  
website:
  title: "Florian Greindl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contact.qmd
    tools:
      - icon: github
        href: https://github.com/FloGre-UGB
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Florian Greindl"

format:
  html:
    theme: yeti
    toc: true

editor: source

